function:
  image: ${IMAGE_NAME}
  triggers:
    - type: azure-blob
      blobContainerName: "processed"
      accountName: "rpesendletter{{ .Values.global.environment }}"
      blobPrefix: ""
